name: Snyk
on:
  pull_request: {}
  push:
    branches: ["master"]
jobs:
  snyk:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g snyk
      - run: npm install
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - run: snyk monitor