name: Snyk

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master"]
jobs:
  # build:
  #   name: build application
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     # Run the "semgrep ci" command on the command line of the docker image.
  #     - name: Use Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - run: npm install
  snyk:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Run the "semgrep ci" command on the command line of the docker image.
      - run: npm i -g snyk
      - run: npm install
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - run: snyk monitor